### ISSUE TITLE
peek-pg ignores prepared statements

### ISSUE THREAD

**Issue by jonah-williams** [peek/peek-pg#2]
I'm starting to plug Peek into an existing app and it has been super helpful. Unfortunately I noticed that pg query counts are dramatically lower than what I'm seeing in developer mode NewRelic reports. I think this is due to peek-pg only instrumenting `exec` and `exec_async` when many calls can instead hit [`exec_cache`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L592) which then calls `send_query_prepared`.

I considered trying to cover all of the possible calls into `PG::Connection` but I think it might be easier and just as useful to use [ActiveSupport Notifications](http://guides.rubyonrails.org/active_support_instrumentation.html#subscribing-to-an-event). I'm guessing peek-pg opted to instrument PG directly to avoid the Rails dependency but I'd love to know if there were other concerns that would make Notifications a poor alternative.

**Comment by lucasmazza** [comment]
Noticed the same thing when adding Peek to Rails 4.2 app - looks like aliasing `exec_prepared` fixed this, but I'm curious if we should take a different approach with `AS::Notifications` like @jonah-williams mentioned.

@dewski any thoughts?
